### ISSUE TITLE
[1.21] Tag the 1.21 version as 1.21.1

### ISSUE THREAD

**Issue by BugmanBugman** [vectorwing/FarmersDelight#965]
### Minecraft version

1.21.1

### Farmer's Delight version

N/A

### NeoForge version

N/A

### Description

Some addons of farmers delight are already on 1.21.1 but this version isnt tagged as such, therefore you cant download it on launchers. Please tag it as 1.21.1 compatible so it works

### Mod list

n/a

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by mpustovoi** [comment]
The mod file for 1.21 already has 1.21.1 in minecraft dependencies, so it should probably work on it.
```toml
[[dependencies.farmersdelight]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,1.21.1)"
    ordering = "NONE"
    side = "BOTH"
```
